// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiceqhHzrqm-lOpwgfCV261_vI5kIwPUY',
    appId: '1:959284886965:web:50fa985378dcea3b7b6dfc',
    messagingSenderId: '959284886965',
    projectId: 'crud-admin-buku',
    authDomain: 'crud-admin-buku.firebaseapp.com',
    storageBucket: 'crud-admin-buku.firebasestorage.app',
    measurementId: 'G-QGMZV0TW1Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9YBviXGRkqk8LUtPqtZYftXSkgAiv3MY',
    appId: '1:959284886965:android:2f078891f75338167b6dfc',
    messagingSenderId: '959284886965',
    projectId: 'crud-admin-buku',
    storageBucket: 'crud-admin-buku.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn6Lz9L6QKSNH6GafaerYS7Ti3LQY1tSE',
    appId: '1:959284886965:ios:14d9d4774690b1327b6dfc',
    messagingSenderId: '959284886965',
    projectId: 'crud-admin-buku',
    storageBucket: 'crud-admin-buku.firebasestorage.app',
    iosBundleId: 'com.example.crudAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn6Lz9L6QKSNH6GafaerYS7Ti3LQY1tSE',
    appId: '1:959284886965:ios:14d9d4774690b1327b6dfc',
    messagingSenderId: '959284886965',
    projectId: 'crud-admin-buku',
    storageBucket: 'crud-admin-buku.firebasestorage.app',
    iosBundleId: 'com.example.crudAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiceqhHzrqm-lOpwgfCV261_vI5kIwPUY',
    appId: '1:959284886965:web:dc5be6880f90986c7b6dfc',
    messagingSenderId: '959284886965',
    projectId: 'crud-admin-buku',
    authDomain: 'crud-admin-buku.firebaseapp.com',
    storageBucket: 'crud-admin-buku.firebasestorage.app',
    measurementId: 'G-Q577237G2N',
  );

}